'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const workflow = fs.readFileSync(path.join(root, '.github', 'workflows', 'windows-build.yml'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

const preload = fs.readFileSync(path.join(root, 'preload.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'src', 'index.html'), 'utf8');
const apiService = fs.readFileSync(path.join(root, 'src', 'services', 'automarket-api-service.js'), 'utf8');
const appSource = fs.readFileSync(path.join(root, 'src', 'app.js'), 'utf8');
const automationService = fs.readFileSync(path.join(root, 'src', 'services', 'automatic-actions-service.js'), 'utf8');
const dealerAvailabilityService = fs.readFileSync(path.join(root, 'src', 'services', 'dealer-availability-service.js'), 'utf8');
const dealerContactService = fs.readFileSync(path.join(root, 'src', 'services', 'dealer-contact-service.js'), 'utf8');
const appointmentCommunicationService = fs.readFileSync(path.join(root, 'src', 'services', 'appointment-communication-service.js'), 'utf8');
const appointmentLibraryService = fs.readFileSync(path.join(root, 'src', 'services', 'appointment-communication-library-service.js'), 'utf8');
assert.equal(preload.includes('integration:inspector'), true);
assert.equal(preload.includes('integration:items'), true);
assert.equal(html.includes('data-testid="api-sync-inspector"'), true);
assert.equal(html.includes('data-testid="ai-control"'), true);
assert.equal(preload.includes('automation:run-now'), true);
assert.equal(apiService.includes('RESOURCE_FIELD_ALLOWLISTS'), true);
assert.equal(apiService.includes('dealer-appointment-availability'), true);
assert.equal(appSource.includes('Website API upgrade required for full two-way chat'), false);
assert.equal(appSource.includes('Automatic cycle skipped: not ready'), false);
assert.equal(appSource.includes('message-ai-toggle'), true);
assert.equal(appSource.includes('message-auto-reply-block'), true);
assert.equal(appSource.includes('notification-open'), true);
assert.equal(automationService.includes('never_edits_existing_customer_records'), true);
assert.equal(automationService.includes('appointment_lead_creation_requires_authorization'), true);
assert.equal(automationService.includes('never_deletes_data'), true);
assert.equal(automationService.includes('NEXA_APPOINTMENT_CONTACT_RECOVERY_V1'), true);
assert.equal(automationService.includes('NEXA_APPOINTMENT_THREAD_LEAD_CREATION_V2'), true);
assert.equal(automationService.includes('NEXA_APPOINTMENT_PAGE_V7_SYNC_V1'), true);
assert.equal(apiService.includes('NEXA_AUTOMARKET_APPOINTMENT_LEADS_V7'), true);
assert.equal(automationService.includes('NEXA_APPOINTMENT_PAGE_V8_SYNC_V1'), true);
assert.equal(automationService.includes('NEXA_APPOINTMENT_REMOTE_COMMIT_VERIFICATION_V1'), true);
assert.equal(automationService.includes('NEXA_STRUCTURED_APPOINTMENT_CONTACT_FORM_V1'), true);
assert.equal(automationService.includes("invalidNames.includes(generic)"), true);
assert.equal(apiService.includes('NEXA_AUTOMARKET_APPOINTMENT_RESERVATION_V8'), true);
assert.equal(appSource.includes('NEXA_AGENDA_REMOTE_RESERVATION_DEDUP_V1'), true);
assert.equal(appSource.includes('Reserve Appointment'), true);
assert.equal(appSource.includes('Open Dealer Appointment Agenda'), true);
assert.equal(appSource.includes('Open Dealer Office Leads'), true);
assert.equal(dealerAvailabilityService.includes('NEXA_LIVE_DEALER_AVAILABILITY_V1'), true);
assert.equal(dealerAvailabilityService.includes('NEXA_APPOINTMENT_CONSISTENCY_GUARD_V1'), true);
assert.equal(dealerAvailabilityService.includes('NEXA_APPOINTMENT_DATE_CONTEXT_RECOVERY_V1'), true);
assert.equal(dealerContactService.includes('NEXA_LIVE_DEALER_CONTACT_V1'), true);
assert.equal(dealerContactService.includes('resolveDealerContact'), true);
assert.equal(appointmentCommunicationService.includes('NEXA_PRO_APPOINTMENT_COMMUNICATION_V1'), true);
assert.equal(appointmentCommunicationService.includes('NEXA_CONTEXTUAL_TIME_SELECTION_V1'), true);
assert.equal(appointmentCommunicationService.includes('NEXA_APPOINTMENT_STATE_MACHINE_V2'), true);
assert.equal(appointmentCommunicationService.includes('same_day'), true);
assert.equal(appointmentCommunicationService.includes('next_day'), true);
assert.equal(appointmentLibraryService.includes('NEXA_BILINGUAL_APPOINTMENT_LIBRARY_V1'), true);
assert.equal(appointmentLibraryService.includes('NEXA_BILINGUAL_APPOINTMENT_STATE_LIBRARY_V2'), true);
assert.equal(appointmentLibraryService.includes('conversationTimePreference'), true);
assert.equal(appointmentLibraryService.includes('isExplicitAppointmentTopicSwitch'), true);
assert.equal(appSource.includes('Live Website Availability'), true);
assert.equal(appSource.includes('dealer-appointment-availability:read scope'), true);

['npm ci', 'npm run validate', 'npm test', 'npm run test:implementation', 'npm run test:acceptance', 'npm run ui:smoke', 'npm run build:win', 'npm run verify:artifacts', 'actions/upload-artifact'].forEach(function requireWorkflowStep(marker) {
  assert.equal(workflow.includes(marker), true, 'Workflow missing: ' + marker);
});
['nsis', 'portable', 'zip'].forEach(function requireTarget(target) {
  const targets = packageJson.build.win.target.map(function targetName(entry) { return typeof entry === 'string' ? entry : entry.target; });
  assert.equal(targets.includes(target), true);
});
console.log('Acceptance tests passed.');
